name: Add PR Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  update-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Check PR Checklist
        run: |
          # Get the pull request number and checklist body from the pull request
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          CHECKLIST_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}" | jq --raw-output .body)

          # Print the checklist body for debugging
          echo "Checklist Body:"
          echo "$CHECKLIST_BODY"

          # Check if all checklist items are checked
          if [[ ! "$CHECKLIST_BODY" =~ "- \\[x\\] Update documentation if necessary" ]]; then
            exit 1
          elif [[ ! "$CHECKLIST_BODY" =~ "- \\[x\\] Run tests to ensure no regressions" ]]; then
            exit 1
          elif [[ ! "$CHECKLIST_BODY" =~ "- \\[x\\] Code review has been performed" ]]; then
            exit 1
          elif [[ ! "$CHECKLIST_BODY" =~ "- \\[x\\] Dependencies have been updated" ]]; then
            exit 1
          elif [[ ! "$CHECKLIST_BODY" =~ "- \\[x\\] Verify backward compatibility" ]]; then
            exit 1
          fi

      - name: Run Additional Steps if Checklist is Checked
        run: |
          # Add additional steps here if you want to perform actions after the checklist is checked
          echo "All checklist items are checked. Proceeding with additional steps."
