name: Validate Checklist

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Description
        run: |
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
                           jq -r '.body')
          echo "::set-env name=PR_DESCRIPTION::$PR_DESCRIPTION"

      - name: Validate Checklist
        run: |
          uncheckedItems=()

          while IFS= read -r line; do
            if [[ "$line" == *" - [ ] "* ]]; then
              uncheckedItems+=("$line")
            fi
          done <<< "${{ env.PR_DESCRIPTION }}"

          if [ ${#uncheckedItems[@]} -gt 0 ]; then
            echo "Unchecked items detected in PR checklist:"
            for item in "${uncheckedItems[@]}"; do
              echo "$item"
            done
            exit 1
          else
            echo "All checklist items are checked in PR"
          fi
