name: Checklist Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checklist_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Description
        id: pr
        run: echo "PR_DESCRIPTION=${{ github.event.pull_request.body }}" >> $GITHUB_ENV

      - name: Check Checklist
        run: |
          uncheckedItems=()

          IFS=$'\n'
          for line in "${{ env.PR_DESCRIPTION }}"; do
            if [[ "$line" == *" - [ ] "* ]]; then
              uncheckedItems+=("$line")
            fi
          done

          if [ ${#uncheckedItems[@]} -gt 0 ]; then
            echo "Unchecked items detected:"
            for item in "${uncheckedItems[@]}"; do
              echo "$item"
            done
            exit 1
          else
            echo "All checklist items are checked"
          fi
