name: Checklist Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: "0 * * * *"

jobs:
  checklist_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Checklist
        run: |
          pr_description=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")

          python3 - <<EOL
          import re
          import sys

          pr_description = '''$pr_description'''

          unchecked_items = []
          lines = pr_description.split('\n')

          for line in lines:
          if re.match(r'^\s*-\s+\[ \]', line):
          unchecked_items.append(line.strip())

          if unchecked_items:
          print("Unchecked items detected:")
          for item in unchecked_items:
           print(item)
          sys.exit(1)
          else:
          print("All checklist items are checked")
          EOL
