name: Validate Checklist

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Description
        id: get_pr_description
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                           "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | \
                           jq -r '.body')
          echo "PR_DESCRIPTION=$PR_DESCRIPTION" >> $GITHUB_ENV

      - name: Validate Checklist
        run: |
          pr_description="${{ steps.get_pr_description.outputs.PR_DESCRIPTION }}"

          unchecked_items=()
          while IFS= read -r line; do
            if [[ "$line" =~ "- \[ \] " ]]; then
              item=$(echo "$line" | sed -E 's/^- \[\ \] //')
              unchecked_items+=("$item")
            fi
          done <<< "$pr_description"

          unchecked_count=${#unchecked_items[@]}
          if [ $unchecked_count -gt 0 ]; then
            echo "Unchecked items detected:"
            for item in "${unchecked_items[@]}"; do
              echo "$item"
            done
            exit 1
          else
            echo "All checklist items are checked in PR"
          fi
