name: Validate Checklist

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  validate_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Checklist
        run: |
          unchecked_items=$(echo "$PR_DESCRIPTION" | grep -o '\[ \] .*')
          if [ -n "$unchecked_items" ]; then
            echo "Unchecked items detected in PR checklist:"
            echo "$unchecked_items"
            exit 1
          else
            echo "All checklist items are checked in PR"
          fi

    env:
      PR_DESCRIPTION: ${{ github.event.pull_request.body }}
