name: Add PR Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  update-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Check checklist
        run: |
          pr_description=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          
          if [[ "$pr_description" =~ "- \\[x\\]" ]]; then
            echo "Unchecked items detected:"
            echo "$pr_description" | grep -oP '- \[ \] \K.+' | sed '/^\s*$/d'
            # Send a notification or take other actions here
            exit 1
          else
            echo "All checklist items are checked"
          fi
