name: Add PR Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  update-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Check PR Checklist
        run: |
          # Get the pull request number
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          # Get the pull request body
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}" | jq --raw-output .body)

          # Check if all checklist items are checked
          CHECKLIST_ITEMS="- [x] Update documentation if necessary  
          - [x] Run tests to ensure no regressions
          - [x] Code review has been performed
          - [x] Dependencies have been updated
          - [x] Verify backward compatibility"

          while read -r item; do
            if [[ ! "$PR_BODY" =~ "$item" ]]; then
              echo "Error: $item not found in checklist."
              exit 1
            fi
          done <<< "$CHECKLIST_ITEMS"


      - name: Run Additional Steps if Checklist is Checked
        run: |
          # Add additional steps here if you want to perform actions after the checklist is checked
          echo "All checklist items are checked. Proceeding with additional steps."
