name: Add PR Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  update-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Check checklist
        run: |
          pr_description=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          
          unchecked_items=$(echo "$pr_description" | grep -oE '\[ \] .+' | sed 's/^\[ \] //')
          
          if [[ -n "$unchecked_items" ]]; then
            echo "Unchecked items detected:"
            echo "$unchecked_items"
            # Send a notification or take other actions here
            exit 1
          else
            echo "All checklist items are checked"
          fi
          echo "All checklist items are checked"
