name: Add PR Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  update-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Check checklist
        run: |
          pr_description=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          checklist_pattern='\[([ x])\] (.+)'

          while IFS= read -r line; do
          if [[ $line =~ $checklist_pattern ]]; then
          status="${BASH_REMATCH[1]}"
          item="${BASH_REMATCH[2]}"
        
          if [ "$status" != "x" ]; then
          echo "Item '$item' is not checked"
          exit 1
          fi
          fi
          done <<< "$pr_description"

          echo "All checklist items are checked"
