name: Checklist Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checklist_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get PR Description
        id: pr
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                           "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | \
                           jq -r '.body')
          echo "::set-output name=description::$PR_DESCRIPTION"

      - name: Check Checklist
        run: |
          PR_DESCRIPTION="${{ steps.pr.outputs.description }}"
          
          unchecked_items=""
          
          IFS=$'\n'
          for line in ${PR_DESCRIPTION}; do
            if [[ $line =~ ^\s*-\s+\[ \] ]]; then
              unchecked_items+="$line\n"
            fi
          done

          if [[ -n "${unchecked_items}" ]]; then
            echo "Unchecked items detected:"
            echo -e "${unchecked_items}"
            exit 1
          else
            echo "All checklist items are checked"
          fi
