name: Update PR Checklist

on:
  issue_comment:
    types: [created]

jobs:
  update-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for Trigger Command
        run: |
          # Get the pull request number
          PR_NUMBER=$(jq --raw-output .issue.pull_request.number "$GITHUB_EVENT_PATH")

          # Check if the comment contains the trigger command
          if jq -e '.comment.body | test("/update-checklist"; "i")' "$GITHUB_EVENT_PATH" > /dev/null; then
            # Define the checklist
            CHECKLIST="- [x] Update documentation if necessary\n- [x] Run tests to ensure no regressions\n- [x] Code review has been performed\n- [x] Dependencies have been updated\n- [x] Verify backward compatibility"

            # Create the updated description with the checklist
            UPDATED_DESCRIPTION=$(jq -n --arg checklist "$CHECKLIST" '{body: $checklist}')

            # Update the pull request description
            curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "$UPDATED_DESCRIPTION" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}"
          fi
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
