name: Validate Checklist

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  validate_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Description
        id: pr
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                           "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | \
                           jq -r '.body')
          echo "::set-output name=pr_description::$PR_DESCRIPTION"

      - name: Validate Checklist
        run: |
          unchecked_items=$(echo "${{ steps.pr.outputs.pr_description }}" | grep -o '\[ \] .*')
          if [ -n "$unchecked_items" ]; then
            echo "Unchecked items detected in PR checklist:"
            echo "$unchecked_items"
            exit 1
          else
            echo "All checklist items are checked in PR"
          fi
